### ISSUE TITLE
Why not use Pod instead?

### ISSUE THREAD

**Issue by leocaseiro** [VideoSpike/nativescript-web-image-cache#2]
Hi, thanks for this amazing plugin.

I'm trying to implement with Angular.
Anyway. I've got the follow error:

`sd_setImageWithURLCompleted is not a function`

So I used Pod to install and it seems working great.

How about replace it to implement using Pod? Isn't a better way to maintain this repo?

**Comment by bathejasumeet** [comment]
Hi, do you mean using . Podfile file instead of .framework file? only reason I didn't use a pod and instead used a static library is because pod didn't work well with NativeScript versions below 2.0, and tns build always failed, throwing errors for Target not specified, which is a requirement for latest pod  and is revamped in 2.0 . I'll look into this and get back at you. If possible, can you provide a link to sample project so I can reproduce the issue?

**Comment by leocaseiro** [comment]
Hi @bathejasumeet,

I removed the platform ios and added it again, so I couldn't reproduce the error again. I really tried.

Anyway!

Instead of having the `platforms/ios/WebImage.framework`, that would much easier with `platforms/ios/Podfile` which would be the simple code bellow and nothing else:

Podfile
```
pod 'SDWebImageCache'
```

Reference: [IQKeyboardManager/platforms/ios/Podfile](https://github.com/tjvantoll/nativescript-IQKeyboardManager/blob/master/platforms/ios/Podfile)

**Comment by bathejasumeet** [comment]
I completely understand it is simple and a norm to use podfile instead of static libraries, I agree with you, when you build it on 2.0 it works perfectly, but when using NativeScript 1.7.2 or 1.6 , the build  fails with podfile. It throws a Target not specified exception. The cocoa pods package manager pod specs changed in between NS 1.7.2 and 2.0 , and to adapt to the latest pod spec changes were made in 2.0.  .Framework file is used for backward compatibility and it is build from same repo using Carthage. Does the problem still persist after adding and removing platform?

**Comment by bathejasumeet** [comment]
Sorry I mean removing and adding platform?

**Comment by leocaseiro** [comment]
It seems working fine for me. We can close the issue.

How about leave the Podfile in a version 2.x for who is using {n} 2.x?

up to you, anyway.

---

PS: I also have a question about the Native [image-cache library from {N}](https://docs.nativescript.org/cookbook/ui/image-cache). Is your library doing a totally different job? Have you used it the {N} one?

I'm sorry asking in the same issue. I'm happy to open another one for this question.

**Comment by bathejasumeet** [comment]
@leocaseiro ,
I would be happy to leave the podfile in N 2.0, will release a new version 2.0 with other upgrades that I wish to work on .
Regarding image-cache library from N - yes , I tried using it, it is cumbersome to cache the images yourself and request for them  and write handlers, it essentially is lot of boilerplate as compared to easy solutions available out there. The second important point is that you can't write multi-threaded code on nativescript currently ( https://github.com/NativeScript/NativeScript/issues/85 ), so you can't create a separate thread and download images in that thread and when complete provide the paths to the original one handling UI, this can be done by native libraries. Please let me know if anything else.

Thanks,
Sumeet.

**Comment by bathejasumeet** [comment]
@leocaseiro ,
Hi,
 as promised I have added Podfile along with other changes to the plugin (though the changes are breaking to support common markup for android)
